// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: F429I_DISC1_SquareLine

#ifndef _F429I_DISC1_SQUARELINE_UI_H
#define _F429I_DISC1_SQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
