// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void moonAni_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_LogoSceen
void ui_LogoSceen_screen_init(void);
lv_obj_t * ui_LogoSceen;
void ui_event_LogoButton(lv_event_t * e);
lv_obj_t * ui_LogoButton;
lv_obj_t * ui_logo;
lv_obj_t * ui_LabelCAMPING;


// SCREEN: ui_SettingSceen
void ui_SettingSceen_screen_init(void);
lv_obj_t * ui_SettingSceen;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Keyboard3;
lv_obj_t * ui_TextArea3;
lv_obj_t * ui_TextArea4;
void ui_event_WifiCall(lv_event_t * e);
lv_obj_t * ui_WifiCall;
lv_obj_t * ui_Label7;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label1;


// SCREEN: ui_MainScene
void ui_MainScene_screen_init(void);
lv_obj_t * ui_MainScene;
lv_obj_t * ui_Image2;
lv_obj_t * ui_MainPanel;
void ui_event_SceneSettingButton(lv_event_t * e);
lv_obj_t * ui_SceneSettingButton;
lv_obj_t * ui_SceneSettingButtonLabel;
void ui_event_SceneMoveButton1(lv_event_t * e);
lv_obj_t * ui_SceneMoveButton1;
lv_obj_t * ui_SceneMoveButtonLabel1;
lv_obj_t * ui_Label6;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
void ui_event_SceneMoveButton3(lv_event_t * e);
lv_obj_t * ui_SceneMoveButton3;
lv_obj_t * ui_SceneMoveButtonLabel3;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label3;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void moonAni_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 10000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 1000);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_LogoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScene, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_MainScene_screen_init);
        moonAni_Animation(ui_Image2, 100);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScene, LV_SCR_LOAD_ANIM_OVER_LEFT, 100, 0, &ui_MainScene_screen_init);
    }
}
void ui_event_WifiCall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        wifiConnetOn(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        WifiCall(e);
    }
}
void ui_event_SceneSettingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingSceen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_SettingSceen_screen_init);
    }
}
void ui_event_SceneMoveButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_SceneMoveButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScene, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MainScene_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_LogoSceen_screen_init();
    ui_SettingSceen_screen_init();
    ui_MainScene_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_LogoSceen);
}
