// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void moonAni_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_LogoSceen
void ui_LogoSceen_screen_init(void);
extern lv_obj_t * ui_LogoSceen;
void ui_event_LogoButton(lv_event_t * e);
extern lv_obj_t * ui_LogoButton;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_LabelCAMPING;
// SCREEN: ui_SettingSceen
void ui_SettingSceen_screen_init(void);
extern lv_obj_t * ui_SettingSceen;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Keyboard3;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_TextArea4;
void ui_event_WifiCall(lv_event_t * e);
extern lv_obj_t * ui_WifiCall;
extern lv_obj_t * ui_Label7;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_MainScene
void ui_MainScene_screen_init(void);
extern lv_obj_t * ui_MainScene;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_MainPanel;
void ui_event_SceneSettingButton(lv_event_t * e);
extern lv_obj_t * ui_SceneSettingButton;
extern lv_obj_t * ui_SceneSettingButtonLabel;
void ui_event_SceneMoveButton1(lv_event_t * e);
extern lv_obj_t * ui_SceneMoveButton1;
extern lv_obj_t * ui_SceneMoveButtonLabel1;
extern lv_obj_t * ui_Label6;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_SceneMoveButton3(lv_event_t * e);
extern lv_obj_t * ui_SceneMoveButton3;
extern lv_obj_t * ui_SceneMoveButtonLabel3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png
LV_IMG_DECLARE(ui_img_moon_png);    // assets/moon.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
