//스퀘어 라인 


#include "ui.h"

void AFunc(lv_event_t * e)  //버튼
{
	 lv_label_set_text(ui_Label4, "slider");
	// Your code here
}

void SwitchFunc01(lv_event_t * e) //토글 스위치 
{

  	bool checked = lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED);
	if (checked)
		lv_label_set_text(ui_Label5, "On");
	else
		lv_label_set_text(ui_Label5, "Off");
    
}

 
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void SwitchFunc01(lv_event_t * e)
{
	bool checked = lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED);
	if (checked)
		lv_label_set_text(ui_Valve1, "On");
	else
		lv_label_set_text(ui_Valve1, "Off");
}

void SwitchFunc02(lv_event_t * e)
{
		bool checked = lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED);
	if (checked)
		lv_label_set_text(ui_Valve2, "On");
	else
		lv_label_set_text(ui_Valve2, "Off");
}

void SwitchFunc03(lv_event_t * e)
{
		bool checked = lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED);
	if (checked)
		lv_label_set_text(ui_Valve3, "On");
	else
		lv_label_set_text(ui_Valve3, "Off");
}

void SwitchFunc04(lv_event_t * e)
{
	bool checked = lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED);
	if (checked)
		lv_label_set_text(ui_Valve4, "On");
	else
		lv_label_set_text(ui_Valve4, "Off");
}
