// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_LogoSceen_screen_init(void)
{
    ui_LogoSceen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LogoSceen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoButton = lv_btn_create(ui_LogoSceen);
    lv_obj_set_width(ui_LogoButton, 582);
    lv_obj_set_height(ui_LogoButton, 300);
    lv_obj_set_x(ui_LogoButton, 5);
    lv_obj_set_y(ui_LogoButton, -3);
    lv_obj_set_align(ui_LogoButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LogoButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_img_create(ui_LogoSceen);
    lv_img_set_src(ui_logo, &ui_img_logo_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_logo, 0);
    lv_obj_set_y(ui_logo, -68);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCAMPING = lv_label_create(ui_LogoSceen);
    lv_obj_set_width(ui_LabelCAMPING, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCAMPING, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCAMPING, 0);
    lv_obj_set_y(ui_LabelCAMPING, 64);
    lv_obj_set_align(ui_LabelCAMPING, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCAMPING, "C A M P I N G");

    lv_obj_add_event_cb(ui_LogoButton, ui_event_LogoButton, LV_EVENT_ALL, NULL);

}
