// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Checkbox1

lv_obj_t * ui_Checkbox1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Checkbox1;
    cui_Checkbox1 = lv_checkbox_create(comp_parent);
    lv_obj_set_width(cui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Checkbox1, -86);
    lv_obj_set_y(cui_Checkbox1, 71);
    lv_obj_set_align(cui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CHECKBOX1_NUM);
    children[UI_COMP_CHECKBOX1_CHECKBOX1] = cui_Checkbox1;
    lv_obj_add_event_cb(cui_Checkbox1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Checkbox1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Checkbox1_create_hook(cui_Checkbox1);
    return cui_Checkbox1;
}

