// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainScene_screen_init(void)
{
    ui_MainScene = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScene, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_MainScene);
    lv_img_set_src(ui_Image2, &ui_img_moon_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 177
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 171
    lv_obj_set_x(ui_Image2, -408);
    lv_obj_set_y(ui_Image2, -213);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 500);

    ui_MainPanel = lv_obj_create(ui_MainScene);
    lv_obj_set_width(ui_MainPanel, 296);
    lv_obj_set_height(ui_MainPanel, 71);
    lv_obj_set_x(ui_MainPanel, 84);
    lv_obj_set_y(ui_MainPanel, 116);
    lv_obj_set_align(ui_MainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MainPanel, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SceneSettingButton = lv_btn_create(ui_MainPanel);
    lv_obj_set_width(ui_SceneSettingButton, 124);
    lv_obj_set_height(ui_SceneSettingButton, 40);
    lv_obj_set_x(ui_SceneSettingButton, 72);
    lv_obj_set_y(ui_SceneSettingButton, 0);
    lv_obj_set_align(ui_SceneSettingButton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SceneSettingButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SceneSettingButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SceneSettingButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SceneSettingButton, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SceneSettingButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SceneSettingButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SceneSettingButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SceneSettingButtonLabel = lv_label_create(ui_SceneSettingButton);
    lv_obj_set_width(ui_SceneSettingButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SceneSettingButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SceneSettingButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SceneSettingButtonLabel, "Wifi Setting");

    ui_SceneMoveButton1 = lv_btn_create(ui_MainPanel);
    lv_obj_set_width(ui_SceneMoveButton1, 101);
    lv_obj_set_height(ui_SceneMoveButton1, 40);
    lv_obj_set_x(ui_SceneMoveButton1, -55);
    lv_obj_set_y(ui_SceneMoveButton1, 0);
    lv_obj_set_align(ui_SceneMoveButton1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SceneMoveButton1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SceneMoveButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SceneMoveButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SceneMoveButton1, lv_color_hex(0x8B8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SceneMoveButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SceneMoveButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SceneMoveButton1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SceneMoveButtonLabel1 = lv_label_create(ui_SceneMoveButton1);
    lv_obj_set_width(ui_SceneMoveButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SceneMoveButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SceneMoveButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SceneMoveButtonLabel1, "Fire");

    ui_Label6 = lv_label_create(ui_MainScene);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 43);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "08:12:10");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SceneSettingButton, ui_event_SceneSettingButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SceneMoveButton1, ui_event_SceneMoveButton1, LV_EVENT_ALL, NULL);

}
