// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingSceen_screen_init(void)
{
    ui_SettingSceen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingSceen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_SettingSceen);
    lv_obj_set_width(ui_Button2, 80);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 193);
    lv_obj_set_y(ui_Button2, 113);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFF8600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "MAIN");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard3 = lv_keyboard_create(ui_SettingSceen);
    lv_obj_set_width(ui_Keyboard3, 365);
    lv_obj_set_height(ui_Keyboard3, 150);
    lv_obj_set_x(ui_Keyboard3, 11);
    lv_obj_set_y(ui_Keyboard3, 49);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_TextArea3 = lv_textarea_create(ui_SettingSceen);
    lv_obj_set_width(ui_TextArea3, 313);
    lv_obj_set_height(ui_TextArea3, 35);
    lv_obj_set_x(ui_TextArea3, 1);
    lv_obj_set_y(ui_TextArea3, -107);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");
    lv_obj_add_flag(ui_TextArea3, LV_OBJ_FLAG_HIDDEN);     /// Flags



    ui_TextArea4 = lv_textarea_create(ui_SettingSceen);
    lv_obj_set_width(ui_TextArea4, 315);
    lv_obj_set_height(ui_TextArea4, 41);
    lv_obj_set_x(ui_TextArea4, 0);
    lv_obj_set_y(ui_TextArea4, -58);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");
    lv_obj_add_flag(ui_TextArea4, LV_OBJ_FLAG_HIDDEN);     /// Flags



    ui_WifiCall = lv_btn_create(ui_SettingSceen);
    lv_obj_set_width(ui_WifiCall, 58);
    lv_obj_set_height(ui_WifiCall, 50);
    lv_obj_set_x(ui_WifiCall, 200);
    lv_obj_set_y(ui_WifiCall, -75);
    lv_obj_set_align(ui_WifiCall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiCall, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_WifiCall, lv_color_hex(0xFF4C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiCall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_WifiCall);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Send");

    ui_Button1 = lv_btn_create(ui_SettingSceen);
    lv_obj_set_width(ui_Button1, 74);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -202);
    lv_obj_set_y(ui_Button1, -75);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF8600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Wifi Scan");

    ui_Label1 = lv_label_create(ui_SettingSceen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -4);
    lv_obj_set_y(ui_Label1, -148);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Wifi Connect");

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard3, ui_TextArea4);
    lv_obj_add_event_cb(ui_WifiCall, ui_event_WifiCall, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
