// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
extern void do_scan();
extern void ui_event_Button4();
void wifiConnetOn(lv_event_t * e)
{
 ui_event_Button4();
	// Your code here
}

void WifiCall(lv_event_t * e)
{do_scan();
	// Your code here
}
